<div id="innlogging">
        <form method="post" action="ProblemDomenet/Behandler.php">
            <table>
                <tr><td>Brukernavn</td><td><input type="text" name="brukernavn" required/></td></tr>
                <tr><td>Passord</td><td><input type="password" name="passord" required/></td></tr>
                <tr><td><input type="submit" name="LoggInn" value="Logg inn"/></td></tr>
            </table>
            
        </form>
    </div>
