<span id="nyttFag">
<img src="img/LeggtilFag.png"/> <span>Legg til nytt fag</span>
    <div id="nyttFagForm">
        <form method="post" action="ProblemDomenet/Behandler.php">
            <table>
            <tr><td>Fagnavn:</td><td><input type="text" name="Fagnavn" required/></td></tr>
            <tr><td>Fagkode:</td><td><input type="text" name="Fagkode"/></td></tr>
            <tr><td>Semester:</td><td><input type="text" name="Semester"/></td></tr>
            <tr><td><input type="submit" name="NyttFag" value="Legg til"/></td></tr>
            </table>
        </form>
    </div>
</span>
