<div id="sideBar">
    <form>
    <h4>Visningsalternativer:</h4>
    <input type="checkbox" name="navn" value="Navn">Navn</br>
    <input type="checkbox" name="URL" value="URL">URL</br>
    <input type="checkbox" name="RSS" value="RSS">RSS</br>
    <input type="checkbox" name="Frekvens" value="Frekvens">Frekvens</br>
    <input type="checkbox" name="Beskrivelse" value="Beskrivelse">Beskrivelse</br>
    </form>
    <form>
        </br>
    <input type="submit" name="Eksporter" value="Eksporter til XML"/>
    <input type="submit" name="SeBlogger" value="Se blogger"/>
    </form>
</div>
